import { StrictMode, useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

type SectionHeaderProps = { number: string; title: string; detail: string }
type RequestComposerProps = { selections: string[]; onClear: () => void; kind: 'service' | 'challenge' }

const currents = [
  ['01', 'Support demand', 'When an issue stops work, people need a quick answer, not another ticket queue.', 'Responsive help desk and proactive monitoring that keeps people moving.'],
  ['02', 'Security pressure', 'Cyber risk is always changing, but everyday protection should not feel complicated.', 'Layered security, clear access controls, and hands-on support.'],
  ['03', 'Cloud movement', 'Your team needs files, systems, and communication tools that work wherever business happens.', 'Cloud tools that are connected, secure, and easy for your people to use.'],
  ['04', 'AI acceleration', 'AI is useful when it solves a real business problem, not when it is just a demo.', 'Practical AI built around the work your team already does.'],
  ['05', 'Workflow friction', 'Repeated emails, manual updates, and handoffs quietly consume valuable time.', 'Simple systems that remove repetitive steps and keep work moving.'],
  ['06', 'Continuity risk', 'A bad day should not become a business interruption.', 'Backups, recovery plans, and monitoring that help you bounce back quickly.'],
  ['07', 'Infrastructure drag', 'Slow networks, poor connectivity, and aging equipment create daily frustration.', 'Reliable networks and equipment designed around how your business works.'],
  ['08', 'Strategic change', 'Technology decisions are easier when every improvement fits a clear plan.', 'A practical roadmap that turns priorities into steady progress.'],
  ['09', 'Unique Challenges', 'Have a specific technology challenge that does not fit neatly into the list?', 'Tell us what is going on and we will help identify the right next step.'],
]

const services = ['AI Automation', 'AI Development', 'Managed IT Services', 'Consulting Services', 'Cybersecurity', 'Cloud Computing', 'Internal AI Assistants', 'AI Customer Experience Tools', 'Document & Data Intelligence', 'AI Governance & Security', 'Backup & Disaster Recovery', 'Cabling & Physical Infrastructure', 'Remote Access & VPN', 'Systems Integration', 'Migrations & Upgrades', 'Help Desk Services', 'Network Design']

const servicePageServices = [
  { number: '01', title: 'Managed IT & Support', summary: 'A dependable IT team that keeps your people productive and your systems healthy.', details: 'We provide responsive help desk support, proactive maintenance, and 24/7 monitoring so technology issues are found and addressed before they slow down the business.', points: ['Help desk and end-user support', '24/7 monitoring and remediation', 'Network management and lifecycle planning'] },
  { number: '02', title: 'Cybersecurity', summary: 'Layered protection that helps reduce risk without making daily work harder.', details: 'Atlantic PC helps protect your people, devices, and business data through managed detection and response, endpoint protection, secure access, awareness training, and modern firewall solutions.', points: ['Managed detection and response', 'Endpoint, email, and identity protection', 'Security awareness and incident response'] },
  { number: '03', title: 'Cloud & Microsoft 365', summary: 'Cloud tools that give your team secure access to the systems and information they need.', details: 'We plan, migrate, secure, and support cloud environments that match how your business operates, from Microsoft 365 and SharePoint to Azure, VMware, and hybrid infrastructure.', points: ['Microsoft 365, SharePoint, and OneDrive', 'Cloud migrations and hybrid environments', 'Secure remote access and collaboration'] },
  { number: '04', title: 'AI Development & Automation', summary: 'Practical AI and connected workflows that remove repetitive work and improve how your business runs.', details: 'We design AI solutions around the real work your team does, from internal assistants and document intelligence to customer experience tools, workflow automation, integrations, and secure governance.', points: ['Internal AI assistants and knowledge tools', 'Workflow automation and systems integration', 'Document intelligence, customer experience AI, and governance'] },
  { number: '05', title: 'Backup & Disaster Recovery', summary: 'Recover quickly when something goes wrong, from a deleted file to a full system failure.', details: 'Our image-based backup and recovery services protect critical systems, applications, and data. We help you restore individual files, complete devices, or entire environments with a tested plan.', points: ['Local and cloud backup', 'Fast file, server, and bare-metal recovery', 'Recovery planning and testing'] },
  { number: '06', title: 'IT Consulting', summary: 'Technology decisions grounded in what will actually help your business move forward.', details: 'Whether you are planning for growth, a new office, a remote workforce, or stronger security, we translate business priorities into an achievable technology roadmap and manage the work to deliver it.', points: ['Technology roadmaps and budgeting', 'Project planning and vendor coordination', 'Growth, relocation, and modernization planning'] },
  { number: '07', title: 'Cabling & Physical Infrastructure', summary: 'The dependable physical foundation behind your network, communications, security, and workplace technology.', details: 'We design and manage structured cabling and low-voltage infrastructure for new construction, renovations, and office improvements, built for today’s needs and tomorrow’s bandwidth.', points: ['Structured cabling and wireless design', 'New offices, renovations, and tenant improvements', 'Scalable infrastructure for voice, data, AV, and security'] },
]

const aiSystems = [
  ['Process automation', 'Reduce repetitive admin, routing, data entry, document handling, approvals and follow-up work.'],
  ['Internal AI assistants', 'Give employees faster access to company knowledge, policies, procedures, client information and operational answers.'],
  ['Customer experience AI', 'Improve response times, triage inbound requests, draft replies, answer common questions and route complex issues.'],
  ['Document intelligence', 'Extract, classify, summarize and act on information from emails, PDFs, forms, contracts, tickets and records.'],
  ['Reporting intelligence', 'Turn scattered business data into summaries, alerts, dashboards, explanations and next-step recommendations.'],
  ['AI governance', 'Define what AI can access, how outputs are checked and how sensitive business data is protected.'],
]

const route = [
  ['01', 'Stabilize', 'Managed IT, help desk, monitoring, remediation.'],
  ['02', 'Secure', 'Cybersecurity, endpoint protection, backup, disaster recovery.'],
  ['03', 'Modernize', 'Cloud, Microsoft 365, infrastructure, remote access.'],
  ['04', 'Automate', 'Workflow automation, integrations, reporting.'],
  ['05', 'Apply AI', 'Assistants, agents, document intelligence, customer experience AI.'],
  ['06', 'Govern & Scale', 'Policies, access control, measurement, optimization.'],
]

const depths = [
  ['Surface', 'Support & Stabilization', 'Help desk, monitoring, remediation and urgent fixes that restore operational calm.'],
  ['100m', 'Security & Continuity', 'Cybersecurity, access controls, backup and disaster recovery that protect the business.'],
  ['500m', 'Cloud & Infrastructure', 'Microsoft 365, cloud, cabling, remote access and network design built for real work.'],
  ['1000m', 'Automation & Integration', 'Connected workflows, system integration, dashboards and reporting that reduce manual workload.'],
  ['3000m', 'Applied AI', 'AI assistants, document intelligence, customer experience AI and process agents.'],
  ['5000m', 'Governed Transformation', 'Policies, measurement, optimization and controlled scaling of intelligent operations.'],
]

const signals = [
  ['Employees keep asking the same questions', 'Knowledge is trapped in people’s heads, documents, inboxes, or shared drives.', 'Internal AI assistant trained on approved company materials, with permissions, source links, and escalation paths.'],
  ['Admin work is eating expensive time', 'Teams spend hours on copy-paste work, data entry, routing, and manual follow-up.', 'Workflow automation and AI agents that extract information, route tasks, draft responses and flag exceptions.'],
  ['Customer support cannot scale', 'Customers need faster answers, but support is expensive and inconsistent.', 'AI customer service layer for triage, FAQs, ticket routing, response drafting and escalation to humans.'],
  ['Managers cannot see what is happening', 'Data is spread across tools, reports are manual and decisions depend on stale information.', 'Dashboards, reporting automation, AI-assisted summaries, alerts and executive visibility across systems.'],
  ['AI tools are being used without control', 'Employees are experimenting with public AI, but the business has no policy or boundaries.', 'AI governance, secure tool selection, access controls and approved AI workflows.'],
  ['IT support is reactive', 'Problems are fixed after they interrupt work.', '24/7 monitoring, remote remediation, root-cause tracking and structured support.'],
]

const partners = [
  { name: 'Microsoft 365', lightLogo: '/media/partners/microsoft-light.png', darkLogo: '/media/partners/microsoft-dark.webp' },
  { name: 'Cisco Meraki', logo: '/media/partners/cisco.svg' },
  { name: 'SonicWall', logo: '/media/partners/sonicwall.svg' },
  { name: 'SentinelOne', lightLogo: '/media/partners/sentinelone-light.svg', darkLogo: '/media/partners/sentinelone-dark.png' },
  { name: 'CrowdStrike', logo: '/media/partners/crowdstrike-light.webp' },
  { name: 'Dell', logo: '/media/partners/dell.svg' },
  { name: 'Datto', logo: '/media/partners/datto.svg' },
  { name: 'Lenovo', logo: '/media/partners/lenovo.svg' },
  { name: 'VMware', logo: '/media/partners/vmware.svg' },
  { name: 'Barracuda', logo: '/media/partners/barracuda-light.png' },
  { name: 'Webroot', lightLogo: '/media/partners/webroot-light.svg', darkLogo: '/media/partners/webroot-dark.png' },
  { name: 'Ubiquiti', logo: '/media/partners/ubiquiti.svg' },
  { name: 'ConnectWise' },
  { name: 'Perch', lightLogo: '/media/partners/perch-light.png', darkLogo: '/media/partners/perch-dark.webp' },
]

function SectionHeader({ number, title, detail }: SectionHeaderProps) {
  return <div className="section-header"><div><span className="section-number">{number}</span><span className="section-title">{title}</span></div><span className="section-detail">{detail}</span></div>
}

function Brand() { return <a className="brand" href="/" aria-label="Atlantic PC home"><img className="brand-logo brand-logo-dark" src="/media/atlantic-pc-dark.png" alt="Atlantic PC" /><img className="brand-logo brand-logo-light" src="/media/atlantic-pc-light.png" alt="" aria-hidden="true" /></a> }

function Header({ light, onToggle }: { light: boolean; onToggle: () => void }) { const [menuOpen, setMenuOpen] = useState(false); return <header><div className="nav-shell"><Brand /><nav aria-label="Primary navigation"><a href="/">Home</a><a href="/services">Services</a></nav><div className="header-actions"><a className="support-link" href="tel:5164178556">Need support? <strong>(516) 417-8556</strong></a><button className="theme-toggle" onClick={onToggle} aria-label={light ? 'Switch to dark mode' : 'Switch to light mode'}>{light ? '◐' : '◑'}</button><a className="button compact" href="tel:5164178556">Talk to us <span>↗</span></a><button className={`menu-toggle ${menuOpen ? 'is-open' : ''}`} type="button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen}><span /><span /><span /></button></div>{menuOpen && <div className="mobile-menu"><a href="/" onClick={() => setMenuOpen(false)}>Home</a><a href="/services" onClick={() => setMenuOpen(false)}>Services</a></div>}</div></header> }

function HeroVideoBackground() { const [allowVideo, setAllowVideo] = useState(false); const [ready, setReady] = useState(false); useEffect(() => { const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches; const connection = (navigator as Navigator & { connection?: { saveData?: boolean } }).connection; setAllowVideo(!reduceMotion && !connection?.saveData); }, []); return <div className={`hero-media ${ready ? 'is-ready' : ''}`} aria-hidden="true">{allowVideo && <video className="hero-video" autoPlay muted loop playsInline preload="metadata" poster="/media/atlantic-wave-poster.jpg" onCanPlay={() => setReady(true)}><source src="/media/atlantic-wave.webm" type="video/webm" /><source src="/media/atlantic-wave.mp4" type="video/mp4" /></video>}<div className="hero-video-overlay" /><div className="hero-video-copy-overlay" /></div> }

function Hero() { return <section id="top" className="hero hero-video-hero"><HeroVideoBackground /><div className="hero-inner hero-single"><div className="hero-copy"><h1>Technology that keeps your business secure, supported, and ready for what’s next.</h1><p className="lede">Atlantic PC manages the technology your business depends on, from IT support and cybersecurity to cloud and practical AI automation. One team to keep things running today and make work easier tomorrow.</p><div className="hero-buttons"><a className="button hero-primary-cta" href="tel:5164178556">Talk to an Atlantic expert <span>↗</span></a></div><div className="hero-mini-proof"><span><b>25+ Years IT Expertise</b></span><i /><span><b>200+ Businesses Trust AtlanticPC</b></span></div></div></div><div className="proof-strip"><div><strong>25<span>+</span></strong><small>YEARS IT EXPERTISE</small></div><div><strong>200<span>+</span></strong><small>BUSINESSES SERVED</small></div><div><strong>97<span>%</span></strong><small>CLIENT SATISFACTION</small></div><div className="proof-location">24/7<br />MONITORING & REMEDIATION <span>→</span></div></div></section> }

function RequestComposer({ selections, onClear, kind }: RequestComposerProps) { const [showContact, setShowContact] = useState(false); const [sent, setSent] = useState(false); const plural = selections.length > 1; const draft = kind === 'service' ? (plural ? `Hey Atlantic PC, I would love to discuss the following services you provide: ${selections.join(', ')}.` : `Hey Atlantic PC, I would love to discuss the ${selections[0]} services you provide.`) : (plural ? `Hey Atlantic PC, I would like help with these business challenges: ${selections.join(', ')}.` : `Hey Atlantic PC, I would like help with ${selections[0]} in my business.`); const [message, setMessage] = useState(draft); return <div className="service-request" aria-live="polite"><div className="service-request-head"><span>{showContact ? 'STEP 2 OF 2 / YOUR CONTACT' : 'STEP 1 OF 2 / YOUR REQUEST'}</span><button type="button" onClick={() => { onClear(); setShowContact(false); setSent(false); }}>Clear selection</button></div>{!sent && !showContact && <><label className="request-message-label" htmlFor={`request-message-${kind}`}>Edit your message</label><textarea id={`request-message-${kind}`} className="request-message" value={message} rows={4} onChange={event => setMessage(event.target.value)} /><button className="button" type="button" onClick={() => setShowContact(true)}>Send request <span>↗</span></button></>}{!sent && showContact && <form onSubmit={event => { event.preventDefault(); setSent(true); }}><h3>Where should we get back to you?</h3><p className="contact-helper">Add an email address or phone number and we’ll connect you with the right person.</p><div className="service-contact-row"><input id={`request-contact-${kind}`} required name="contact" aria-label="Email address or phone number" placeholder="Email address or phone number" /><button className="button" type="submit">Send request <span>↗</span></button></div><button className="back-step" type="button" onClick={() => setShowContact(false)}>← Back to your request</button></form>}{sent && <div className="service-success"><span>REQUEST SENT</span><strong>Thanks, Atlantic PC will be in touch shortly.</strong><p>Your selected {plural ? 'items have' : 'item has'} been included in the request.</p></div>}</div> }

function Currents() { const [selected, setSelected] = useState<string[]>([]); const requestRef = useRef<HTMLDivElement>(null); useEffect(() => { if (selected.length > 0 && window.matchMedia('(max-width: 700px)').matches) requestRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }, [selected.length]); const toggleChallenge = (title: string) => setSelected(current => current.includes(title) ? current.filter(item => item !== title) : [...current, title]); return <section className="section currents-section chart-bg"><div className="container"><SectionHeader number="01" title="BUSINESS CHALLENGES" detail="COMMON TECHNOLOGY PROBLEMS WE HELP SOLVE"/><div className="headline-block"><h2>What is getting in the way of your business?</h2><p>Technology problems usually show up as lost time, frustrated staff, customer delays, or uncertainty about what to do next. Atlantic turns those everyday challenges into a clear, manageable plan.</p></div><div className="current-grid">{currents.map(([number, title, text, response]) => <button type="button" className={`current-card ${selected.includes(title) ? 'is-selected' : ''}`} aria-pressed={selected.includes(title)} onClick={() => toggleChallenge(title)} key={number}><span>{number} / CHALLENGE</span><h3>{title}</h3><p>{text}</p><div className="current-response"><small>HOW ATLANTIC HELPS</small><b>{response}</b></div></button>)}</div>{selected.length > 0 && <div ref={requestRef}><RequestComposer key={selected.join('|')} selections={selected} kind="challenge" onClear={() => setSelected([])} /></div>}</div></section> }

function ServiceRange() { const [selected, setSelected] = useState<string[]>([]); const [showAll, setShowAll] = useState(false); const toggleService = (service: string) => setSelected(current => current.includes(service) ? current.filter(item => item !== service) : [...current, service]); return <section id="services" className="section service-range"><div className="container"><SectionHeader number="02" title="OUR TECHNOLOGY SERVICES" detail="IT SUPPORT · SECURITY · CLOUD · BUSINESS AUTOMATION"/><div className="split-intro"><h2>A full operating service for business technology.</h2><p>Atlantic PC combines frontline support with strategic consulting and AI development, so clients get fast issue resolution, secure infrastructure, and a practical route toward AI-enabled operations.</p></div><div className={`pills service-selector ${showAll ? 'is-expanded' : 'is-collapsed'}`}>{services.map(service => <button className={selected.includes(service) ? 'is-selected' : ''} type="button" aria-pressed={selected.includes(service)} onClick={() => toggleService(service)} key={service}>{selected.includes(service) && <span aria-hidden="true">✓</span>}{service}</button>)}</div><button className="service-show-more" type="button" onClick={() => setShowAll(!showAll)}>{showAll ? 'Show fewer services' : 'Show more services'} <span>{showAll ? '↑' : '↓'}</span></button>{selected.length > 0 && <RequestComposer key={selected.join('|')} selections={selected} kind="service" onClear={() => setSelected([])} />}</div></section> }

function AppliedAI() { return <section id="ai" className="section ai-section chart-bg"><div className="container"><SectionHeader number="03" title="APPLIED AI" detail="WORKFLOW AUTOMATION / ASSISTANTS · AGENTS · GOVERNANCE"/><div className="headline-block ai-intro"><h2>AI that works inside the business, not outside it.</h2><p>Most companies do not need another AI demo. They need practical systems that connect to their real workflows, documents, customers, staff, and operating processes. Atlantic PC builds AI solutions on top of the technology foundation businesses already use, securely, measurably, and with human control where it matters.</p></div><div className="ai-grid">{aiSystems.map(([title, text], index) => <article className="ai-card" key={title}><span>AI / 0{index + 1}</span><h3>{title}</h3><p>{text}</p><a href="#contact" aria-label={`Discuss ${title}`}>Explore system <b>→</b></a></article>)}</div></div></section> }

function CrossingRoute() { return <section id="route" className="section route-section chart-bg"><div className="container"><SectionHeader number="03" title="YOUR TECHNOLOGY ROADMAP" detail="A PRACTICAL PATH FROM SUPPORT TO SMARTER OPERATIONS"/><div className="split-intro"><h2>A controlled route from support to transformation.</h2><p>Atlantic helps clients move in phases: first stabilizing and securing the technology environment, then modernizing systems, automating workflows, applying AI where it creates measurable value, and governing the result.</p></div><div className="route-map">{route.map(([number, title, text]) => <article key={number}><span className="route-dot" /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section> }

function DepthScale() { return <section className="section depth-section"><div className="container"><SectionHeader number="05" title="DEPTH OF ENGAGEMENT" detail="FROM SURFACE SUPPORT TO FULL AI-ENABLED OPERATIONS"/><div className="depth-layout"><div className="depth-copy"><h2>Go as deep as the business requires.</h2><p>Some clients need reliable support and security. Others need cloud modernization, workflow redesign, custom AI systems, and long-term governance. Atlantic can engage at the depth required.</p><div className="depth-readout"><span>ACTIVE DEPTH</span><strong>5000m</strong><p>GOVERNED TRANSFORMATION</p></div></div><div className="depth-scale">{depths.map(([depth, title, text], i) => <article key={depth}><div className="depth-marker"><b>{depth}</b><i /></div><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></div></section> }

function SignalSystem() { return <section id="signal" className="section signal-section chart-bg"><div className="container"><SectionHeader number="04" title="FROM PROBLEM TO SOLUTION" detail="TURNING DAY-TO-DAY FRUSTRATION INTO PRACTICAL IMPROVEMENTS"/><div className="headline-block"><h2>Recognize the signal. Build the system around it.</h2><p>Most technology problems show up first as frustration: slow support, exposed systems, scattered cloud tools, manual workflows, unreliable backup, weak remote access, or AI being used without control. Atlantic translates those signals into practical operating systems.</p></div><div className="signal-grid">{signals.map(([signal, diagnosis, system]) => <article className="signal-card" key={signal}><h3>{signal}</h3><div><small>DIAGNOSIS</small><p>{diagnosis}</p></div><div className="system-result"><small>SYSTEM</small><p>{system}</p></div></article>)}</div></div></section> }

function Ecosystem() { return <section className="section ecosystem"><div className="container"><SectionHeader number="05" title="TECHNOLOGY PARTNERS" detail="THE PLATFORMS YOUR BUSINESS MAY ALREADY USE"/><div className="split-intro"><h2>Aligned with the platforms businesses already rely on.</h2><p>Atlantic PC supports the practical technology stack behind your operations and helps it evolve without disruption.</p></div><div className="partners">{partners.map(partner => <div className={`partner-badge ${partner.logo || partner.lightLogo ? 'has-logo' : 'text-only'}`} key={partner.name}>{partner.logo && <img className="partner-logo" src={partner.logo} alt={partner.name} />}{partner.lightLogo && <><img className="partner-logo partner-logo-light" src={partner.lightLogo} alt={partner.name} /><img className="partner-logo partner-logo-dark" src={partner.darkLogo} alt="" aria-hidden="true" /></>}{!partner.logo && !partner.lightLogo && <span className="partner-name">{partner.name}</span>}</div>)}</div></div></section> }

function Proof() { const quotes = [{ quote: '“Quick response and my issue was fixed immediately.”', name: 'Jordan Lee', company: 'North Shore Dental Group', initials: 'JL' }, { quote: '“The support team handled the issue really well and resolved it incredibly fast.”', name: 'Priya Shah', company: 'Harbor Financial Partners', initials: 'PS' }, { quote: '“Great fix on the root cause rather than just the problem.”', name: 'Michael Torres', company: 'Brightline Manufacturing', initials: 'MT' }, { quote: '“Moved our entire office with only 3 hours of downtime, what a win!”', name: 'Danielle Brooks', company: 'Brooks & Co. Law', initials: 'DB' }]; return <section id="proof" className="section proof-section"><div className="container"><SectionHeader number="06" title="CLIENT RESULTS" detail="WHAT CLIENTS SAY ABOUT WORKING WITH ATLANTIC PC"/><div className="proof-top"><h2>Proof in the signal.</h2></div><div className="quotes">{quotes.map(({ quote, name, company, initials }) => <figure key={quote}><blockquote>{quote}</blockquote><figcaption><span className="testimonial-person"><i aria-hidden="true">{initials}</i><span><b>{name}</b><small>{company}</small></span></span></figcaption></figure>)}</div></div></section> }

function AtticusCreditFooter() { return <div className="atticus-credit" aria-label="Developed by Atticus AI Lab"><div className="atticus-credit-line" /><a href="https://atticusailab.com/" target="_blank" rel="noreferrer"><span>Developed with</span><svg className="atticus-heart" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21s-7.5-4.6-9.6-9.2C.9 8.3 2.6 4.6 6 4.1c2.1-.3 4 .8 6 3 2-2.2 3.9-3.3 6-3 3.4.5 5.1 4.2 3.6 7.7C19.5 16.4 12 21 12 21z" /></svg><span>by</span><strong>Atticus AI Lab</strong><img src="/media/atticus-favicon.png" alt="" aria-hidden="true" loading="lazy" /></a><small>© 2026 Atticus AI Lab</small></div> }

function CTA() { return <section id="contact" className="cta chart-bg"><div className="container"><SectionHeader number="07" title="START A CONVERSATION" detail="A SIMPLE CONVERSATION IS THE BEST PLACE TO START"/><div className="cta-main"><div><h2>Let’s make technology easier for your business.</h2><p>Tell us what is not working, what you want to improve, or where you are curious about AI. We will help you identify a clear, practical next step.</p></div><div className="cta-actions"><a className="button" href="tel:5164178556">Talk to us <span>↗</span></a><a className="button ghost" href="mailto:hello@atlanticny.com?subject=Let%27s%20Talk">Request a callback <span>↗</span></a><a className="text-link" href="tel:5164178556">Need support now? <span>→</span></a></div></div><footer><Brand /><address>55 Northern Blvd. Suite 305<br />Great Neck, NY 11021</address></footer><AtticusCreditFooter /></div></section> }

function ServicesPage() { const [selectedService, setSelectedService] = useState<string | null>(null); return <><section className="services-hero hero-video-hero"><HeroVideoBackground /><div className="container services-hero-inner"><h1>Smarter systems for the way your business works.</h1><p>From everyday IT support and cybersecurity to cloud, recovery, infrastructure, and practical AI, Atlantic PC gives your business one accountable team for the systems it relies on.</p><div className="hero-buttons"><a className="button" href="tel:5164178556">Talk to an Atlantic expert <span>↗</span></a><a className="button ghost" href="#service-list">Explore services <span>↓</span></a></div></div></section><section id="service-list" className="section services-detail chart-bg"><div className="container"><SectionHeader number="01" title="OUR SERVICES" detail="HOW ATLANTIC PC CAN SUPPORT YOUR BUSINESS"/><div className="service-detail-list">{servicePageServices.flatMap(service => [<article id={`service-${service.number}`} key={service.number} className={selectedService === service.title ? 'is-discussing' : undefined}><div className="service-detail-number">{service.number}</div><div><h2>{service.title}</h2><h3>{service.summary}</h3><p>{service.details}</p><ul>{service.points.map(point => <li key={point}>{point}</li>)}</ul><button className="text-link inline-text-button" type="button" onClick={() => setSelectedService(service.title)}>Discuss this service <span>↗</span></button></div></article>, selectedService === service.title ? <div className="service-detail-request" key={`${service.number}-request`}><RequestComposer key={service.title} selections={[service.title]} kind="service" onClear={() => setSelectedService(null)} /></div> : null])}</div></div></section><section className="services-cta"><div className="container"><div><p className="eyebrow">START WITH A CONVERSATION</p><h2>Not sure where to begin?</h2><p>Tell us what is slowing your team down or what you want to improve. We will help you identify the right next step.</p></div><a className="button" href="tel:5164178556">Talk to us <span>↗</span></a></div><AtticusCreditFooter /></section></> }

function App() { const [light, setLight] = useState(true); const isServicesPage = window.location.pathname === '/services'; return <div className={light ? 'theme-light' : undefined}><Header light={light} onToggle={() => setLight(!light)} /><main>{isServicesPage ? <ServicesPage /> : <><Hero /><Currents /><ServiceRange /><CrossingRoute /><SignalSystem /><Ecosystem /><Proof /><CTA /></>}</main></div> }

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
